# Generated by Django 5.2.10 on 2026-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_borrower_remove_user_is_lender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='If true, the user is barred from applying for new loans.'),
        ),
    ]
