# Generated by Django 5.2.10 on 2026-01-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
