# Generated by Django 5.2.10 on 2026-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20),
        ),
    ]
